name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # The pipeline will be triggered on a push to the main branch.

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the code from the repository.

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4 # Go version used in the project.

    - name: Install dependencies
      run: |
        cd fullAPI  # Change directory to ./fullAPI where main.go is located.
        go mod tidy  # Ensures that all dependencies are installed.

    - name: Build Go executable
      run: |
        cd fullAPI  # Change to ./fullAPI directory.
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bootstrap main.go
        # Build the Go executable compatible with AWS Lambda.

    - name: Zip executable
      run: |
        cd fullAPI  # Make sure we are in the correct directory.
        zip bootstrap.zip bootstrap
        # Compresses the executable into a deployment.zip file for Lambda.

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.2.0 # Using the action from appleboy
      with:
        function_name: API  # Name of your Lambda function.
        zip_file: ./fullAPI/bootstrap.zip  # Use the zip file created in ./fullAPI.
        region: sa-east-1        # The region where your Lambda is hosted.
        profile: default                  # Optional: Provide the AWS profile to use.
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key.
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key.
